AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Globals:
    Api:
        Cors:
            AllowMethods: "'GET,POST,OPTIONS'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
            # AllowCredentials: true  Uncomment only if you choose a specific origin instead of the * wildcard.

Resources:
  TCRequestsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60  # Increase the timeout to 60 seconds
      Events:
        GetWord:
          Type: Api 
          Properties:
            Path: /getWord
            Method: get
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'content-type'"
              AllowOrigin: "'http://localhost:5001'"  # Replace with your frontend's origin
        CheckAnswer:
          Type: Api 
          Properties:
            Path: /checkAnswer
            Method: post
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'content-type'"
              AllowOrigin: "'http://localhost:5001'"  # Replace with your frontend's origin

Outputs:
  TCApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TCRequestsFunction:
    Description: "Function for making requests pertaining to Thousand Challenge"
    Value: !GetAtt TCRequestsFunction.Arn
  TCRequestsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TCRequestsFunctionRole.Arn
