AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  TCRequestsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 60  # Increase the timeout to 60 seconds
      Events:
        GetWord:
          Type: Api 
          Properties:
            Path: /getWord
            Method: get
        CheckAnswer:
          Type: Api 
          Properties:
            Path: /checkAnswer
            Method: post

Outputs:
  TCApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TCRequestsFunction:
    Description: "Function for making requests pertaining to Thousand Challenge"
    Value: !GetAtt TCRequestsFunction.Arn
  TCRequestsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TCRequestsFunctionRole.Arn
